#!/usr/bin/python
import ROOT, sys, os

for l in [x for x in os.listdir(os.environ['LARCV_LIBDIR']) if x.endswith('.so')]:
   ROOT.gSystem.Load('%s/%s' % (os.environ['LARCV_LIBDIR'],l))

from ROOT import larcv

if len(sys.argv) < 2:

   print 'Usage: python',sys.argv[0],'CONFIG_FILE'
   sys.exit(1)

proc = larcv.ProcessDriver('ProcessDriver')
print "Configuring with {}".format(sys.argv[1])
proc.configure(sys.argv[1])

proc.initialize()

proc.process_entry()

proc.finalize()
